FROM fabric8/java-centos-openjdk11-jdk

#get geckodriver and untar geckodriver
# wget https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
# tar -xf geckodriver-v0.26.0-linux64.tar.gz
# mv geckodriver /usr/local/bin/

RUN yum update -y; \
    yum install -y wget unzip curl vim python-setuptools sudo; \
    easy_install supervisor
RUN wget https://download.java.net/openjdk/jdk${JAVA_VER}/ri/openjdk-${JAVA_VER}+28_linux-x64_bin.tar.gz -O /opt/jdk.tar.gz

RUN cd /opt; \
    tar -xvf jdk.tar.gz; \
    rm jdk.tar.gz
    
COPY /target/docker/monitoring-0.1-SNAPSHOT-onejar.jar /deployments/onejar.jar 